-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."sessions_session_tags" add column "id" serial
--  not null unique;
