# $sessionsWhere: SessionsWhereInput
query GetUsers {
  findManyUsers {
    id
    auth_id
    user_name
    name
    # sessions(where: $sessionsWhere) {
    #   title
    #   started_at
    #   ended_at
    #   tags {
    #     tag {
    #       label
    #     }
    #   }
    #   author {
    #     email
    #     name
    #   }
    # }
  }
}
