import type { GetStaticPropsContext, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import styles from '../styles/Top.module.scss'
import Login from '@web/components/Login'
import Calendar from '@web/components/Calendar'
import { getSessionList } from '@web/usecases/topUsecase'
import { useState, useContext } from 'react'
import SessionSearchContext from '@web/contexts/SessionSearchContext'
import dayjs from 'dayjs'

type ContainerProps = InferGetStaticPropsType<typeof getStaticProps>
type Props = ReturnType<typeof useContainer>

const Presenter: React.VFC<Props> = ({
  eventDates,
  onClickCalendarDay,
  searchResults,
}) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Login />
    <Calendar eventDates={eventDates} onClickDay={onClickCalendarDay} />
    {JSON.stringify(searchResults)}
  </div>
)

const useContainer = (props: ContainerProps) => {
  const { sessions, setQuery, searchResults } = useContext(SessionSearchContext)

  const eventDates = sessions.map((session) => session.startAt)
  const onClickCalendarDay = (value: Date) => {
    setQuery({ date: dayjs(value).unix() })
  }

  const presenterProps = {
    eventDates,
    searchResults,
    onClickCalendarDay,
  }

  return {
    ...props,
    ...presenterProps,
  }
}

export const getStaticProps = async (ctx: GetStaticPropsContext) => {
  return {
    props: {},
    revalidate: 1,
  }
}

export default function Index(props: ContainerProps) {
  return <Presenter {...useContainer(props)} />
}
