import type {
  NextPage,
  GetStaticPropsContext,
  InferGetStaticPropsType,
} from 'next'
import Head from 'next/head'
import styles from '../styles/Top.module.scss'
import Login from '@web/components/Login'
import Calendar from '@web/components/Calendar'
import { getSessionList } from '@web/usecases/topUsecase'
import { ComponentProps } from 'react'

type ContainerProps = InferGetStaticPropsType<typeof getStaticProps>
type Props = ReturnType<typeof useContainer>

const Presenter: React.VFC<Props> = ({ sessionList }) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Login />
    <Calendar />
  </div>
)

const useContainer = (props: ContainerProps) => {
  const a = 1

  return {
    ...props,
    a,
  }
}

export const getStaticProps = async (ctx: GetStaticPropsContext) => {
  const sessionList = await getSessionList()

  return {
    props: {
      sessionList,
    },
    revalidate: 60,
  }
}

export default function Index(props: ContainerProps) {
  return <Presenter {...useContainer(props)} />
}
