version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./docker:/var/lib/postgresql/data
    env_file:
      - ./.env
      - ./.env.development
      - ./.env.development.local
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.0.9
    ports:
      - '8081:8080'
    depends_on:
      - 'postgres'
    restart: always
    env_file:
      - ./.env
      - ./.env.development
      - ./.env.development.local
